version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - DB_HOST=db
      - DB_PORT=$DB_PORT
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - JWT_SECRET=$JWT_SECRET
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USERNAME=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
